package com.e4u.learning_service.entities;

import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Entity representing contextual examples for words.
 * Supports both system-generated and user-specific contexts.
 * Part of the static vocabulary layer - reusable across users.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name = "word_context_templates", indexes = {
        @Index(name = "idx_context_lookup", columnList = "word_id, created_for_user_id"),
        @Index(name = "idx_context_unit", columnList = "unit_id")
})
public class WordContextTemplate extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unit_id")
    private CurriculumUnit unit;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "word_id", nullable = false)
    private GlobalDictionary word;

    /**
     * Lesson templates that use this word context (inverse side of ManyToMany)
     */
    @ManyToMany(mappedBy = "wordContextTemplates", fetch = FetchType.LAZY)
    @Builder.Default
    private Set<LessonTemplate> lessonTemplates = new HashSet<>();

    @Column(name = "specific_meaning", length = 255)
    private String specificMeaning;

    @Column(name = "context_sentence", columnDefinition = "TEXT", nullable = false)
    private String contextSentence;

    @Column(name = "context_translation", columnDefinition = "TEXT")
    private String contextTranslation;

    @Column(name = "ai_reasoning", columnDefinition = "TEXT")
    private String aiReasoning;

    @Enumerated(EnumType.STRING)
    @Column(name = "source_type", length = 50)
    @Builder.Default
    private SourceType sourceType = SourceType.SYSTEM;

    /**
     * If NULL: This is a system/shared context available to all users.
     * If has value: This is a custom context created for a specific user.
     */
    @Column(name = "created_for_user_id")
    private UUID createdForUserId;

    public enum SourceType {
        SYSTEM, // Created by system/admin
        AI_GENERATED, // Generated by AI based on user's goal
        USER_EXTENSION // Created by user via browser extension
    }

    /**
     * Check if this context is a shared/system context
     */
    public boolean isSharedContext() {
        return createdForUserId == null;
    }

    /**
     * Check if this context belongs to a specific user
     */
    public boolean isUserSpecificContext(UUID userId) {
        return createdForUserId != null && createdForUserId.equals(userId);
    }
}
